### ISSUE TITLE
S1 Get Travis CI figured out

### ISSUE THREAD

**Issue by cthaden** [justinak/ssw690Spring2018#10]

**Comment by kxue4** [comment]
.trivis.yml file created, need Justina to sign in [travis-ci.org](url) with personal Github account.

**Comment by latinocodes** [comment]
I connected the results to github

**Comment by latinocodes** [comment]
I know the problem with travis, but can't fix it because the master is blocking me from submitting. please accept all merges to the master.

**Comment by kxue4** [comment]
I figured out why Trivis Ci build failed and updated .travis.yml, it's passing now.
