### ISSUE TITLE
S1 W2 Upload video to Mobile App

### ISSUE THREAD

**Issue by justinak** [justinak/ssw690Spring2018#24]

**Comment by latinocodes** [comment]
I don't get this one, isn't it suppose to be the other way around?

**Comment by cthaden** [comment]
We want to pretend to be a user and upoad our own video.

**Comment by cthaden** [comment]
We finally decided the YouTube APIs will be called in Flask. I will get this coded this week.

**Comment by latinocodes** [comment]
Th portion of the streaming from aws - completed. performing searches from youtube api - completed.
