### ISSUE TITLE
S1 Mock up (wire frame) for iOS app

### ISSUE THREAD

**Issue by cthaden** [justinak/ssw690Spring2018#9]

**Comment by baekim** [comment]
iOS WireFrame
Vincent Porta
-Register Screen
-Interview Question Screen
-User Feed/Profile Screen

Michael Kim
-Login Screen
-Welcome Screen
-Video Screen

**Comment by vporta** [comment]
[iPhone.pdf](https://github.com/justinak/ssw690Spring2018/files/1756580/iPhone.pdf)
Mockups^
